#!/bin/bash

# Get the real basedir by resolving any links.
basedir=$(dirname "$(readlink -e "$0")")

# Include further functions.
source "$basedir/gitary-functions" || exit 1

# Use default settings as fallback.
default_prefix=${XDG_DATA_HOME:-$HOME/.local/share}
datadir=${GITARY_DATA:-$default_prefix/gitary}
editor=${EDITOR:-vim}
pager=${PAGER:-less}

# Check if the user only wants to view the help page. If so, display it
# and exit. This does not check whether the data dir exists.
case "$1" in
	help|-h|-help|--help)
		man -M "$basedir" gitary
		exit 1
		;;
esac

# Okay, now check the data dir and process all other options.
checkdatadir

case "$1" in
	tags|-tags|--tags)
		# Only search for tags.
		shift
		search "$@"
		;;
	refs|-refs|--refs)
		# Only search for references.
		shift
		search -r "$@"
		;;
	search|-search|--search)
		# Search whole entries.
		shift
		search -a "$@"
		;;
	gitk|-gitk|--gitk)
		(
			cd "$datadir"
			gitk --all
		)
		;;
	edit|-edit|--edit|view|-view|--view)
		# Edit or create an arbitrary entry.
		shift
		edit "$1.gitary"
		;;
	viewall|-viewall|--viewall)
		# Show all entries in chronological order.
		viewall
		;;
	topics|-topics|--topics)
		# Show all topics. A time range may be given as an optional
		# argument.
		shift
		topics "$@"
		;;
	*)
		# Create a new entry for today.
		edit "$(date +%F).gitary"
		;;
esac

# vim: set ts=4 sw=4 :
